# Generated by Django 5.2.16 on 2026-08-26 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to='reading/resources/')),
                ('level', models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=2, null=True)),
                ('category', models.CharField(choices=[('ARTICLE', 'Article'), ('BOOK', 'Book'), ('LESSON', 'Lesson'), ('STORY', 'Story')], max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReadingAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PROCESSING', max_length=20)),
                ('difficulty_profile', models.JSONField(blank=True, default=dict)),
                ('vocabulary_profile', models.JSONField(blank=True, default=dict)),
                ('quality_profile', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('system_resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reading.readingresource')),
            ],
        ),
        migrations.CreateModel(
            name='ReadingSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('data', models.JSONField()),
                ('order', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='reading.readinganalysis')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ReadingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_progresses', to=settings.AUTH_USER_MODEL)),
                ('system_resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reading.readingresource')),
                ('completed_sections', models.ManyToManyField(blank=True, related_name='completed_by_users', to='reading.readingsection')),
            ],
        ),
        migrations.CreateModel(
            name='ReadingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField(default=0, help_text='Duration in seconds')),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='reading.readingprogress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserReadingResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='reading/user_resources/')),
                ('category', models.CharField(choices=[('ARTICLE', 'Article'), ('BOOK', 'Book'), ('LESSON', 'Lesson'), ('STORY', 'Story')], max_length=20)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_uploads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='readingprogress',
            name='user_resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reading.userreadingresource'),
        ),
        migrations.AddField(
            model_name='readinganalysis',
            name='user_resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reading.userreadingresource'),
        ),
        migrations.CreateModel(
            name='NotebookItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('VOCABULARY', 'Vocabulary'), ('GRAMMAR', 'Grammar'), ('PHRASE', 'Phrase')], max_length=20)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notebook_items', to=settings.AUTH_USER_MODEL)),
                ('system_resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reading.readingresource')),
                ('user_resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reading.userreadingresource')),
            ],
        ),
        migrations.AddConstraint(
            model_name='readingprogress',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('system_resource__isnull', False), ('user_resource__isnull', True)), models.Q(('system_resource__isnull', True), ('user_resource__isnull', False)), _connector='OR'), name='reading_progress_exactly_one_resource'),
        ),
        migrations.AddConstraint(
            model_name='readinganalysis',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('system_resource__isnull', False), ('user_resource__isnull', True)), models.Q(('system_resource__isnull', True), ('user_resource__isnull', False)), _connector='OR'), name='reading_analysis_exactly_one_resource'),
        ),
        migrations.AddConstraint(
            model_name='notebookitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('system_resource__isnull', False), ('user_resource__isnull', True)), models.Q(('system_resource__isnull', True), ('user_resource__isnull', False)), _connector='OR'), name='reading_notebook_exactly_one_resource'),
        ),
    ]
