# Generated by Django 5.2.16 on 2026-08-19 07:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakingExercise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('exercise_type', models.CharField(choices=[('roleplay', 'Roleplay'), ('freeform', 'Freeform'), ('storytelling', 'Storytelling'), ('shadowing', 'Shadowing'), ('pronunciation', 'Pronunciation Drill')], max_length=20)),
                ('cefr_level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=2)),
                ('coaching_style', models.CharField(choices=[('supportive', 'حمایتی'), ('balanced', 'متعادل'), ('strict', 'سخت\u200cگیرانه')], max_length=20)),
                ('estimated_minutes', models.PositiveSmallIntegerField()),
                ('is_recommended', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpeakingTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpeakingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='speaking.speakingexercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SpeakingEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('score', models.FloatField(blank=True, null=True)),
                ('analysis', models.JSONField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='speaking.speakingsession')),
            ],
        ),
        migrations.AddField(
            model_name='speakingexercise',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='exercises', to='speaking.speakingtag'),
        ),
        migrations.CreateModel(
            name='SpeakingTurn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('speaker', models.CharField(choices=[('ai', 'AI'), ('user', 'User')], max_length=10)),
                ('order', models.PositiveIntegerField()),
                ('text', models.TextField(blank=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='speaking/audio/%Y/%m/')),
                ('audio_format', models.CharField(blank=True, max_length=10)),
                ('audio_size_bytes', models.PositiveIntegerField(blank=True, null=True)),
                ('audio_duration_seconds', models.FloatField(blank=True, null=True)),
                ('transcription_status', models.CharField(choices=[('n/a', 'N/A'), ('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='n/a', max_length=20)),
                ('transcription_raw', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='speaking.speakingsession')),
            ],
            options={
                'ordering': ['session', 'order'],
            },
        ),
        migrations.AddIndex(
            model_name='speakingsession',
            index=models.Index(fields=['user', 'status'], name='speaking_sp_user_id_254a56_idx'),
        ),
        migrations.AddIndex(
            model_name='speakingsession',
            index=models.Index(fields=['user', 'started_at'], name='speaking_sp_user_id_44af25_idx'),
        ),
        migrations.AddIndex(
            model_name='speakingexercise',
            index=models.Index(fields=['exercise_type', 'is_active'], name='speaking_sp_exercis_154f30_idx'),
        ),
        migrations.AddIndex(
            model_name='speakingexercise',
            index=models.Index(fields=['cefr_level'], name='speaking_sp_cefr_le_06eee6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='speakingturn',
            unique_together={('session', 'order')},
        ),
    ]
