# Generated by Django 5.2.16 on 2026-08-02 17:44

import apps.listening.models
import apps.listening.validators
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeningContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('content_type', models.CharField(choices=[('podcast', 'Podcast'), ('conversation', 'Conversation'), ('story', 'Story'), ('news', 'News'), ('interview', 'Interview'), ('lecture', 'Lecture'), ('exam', 'Exam'), ('custom', 'Custom')], max_length=20)),
                ('source_type', models.CharField(choices=[('platform', 'Platform'), ('user_upload', 'User upload'), ('external_url', 'External URL')], default='platform', max_length=20)),
                ('cefr_level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=2)),
                ('accent', models.CharField(choices=[('american', 'American'), ('british', 'British'), ('australian', 'Australian'), ('canadian', 'Canadian'), ('mixed', 'Mixed'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('processing', 'Processing'), ('coming_soon', 'Coming soon')], default='processing', max_length=16)),
                ('transcription_language', models.CharField(default='en', max_length=10, validators=[django.core.validators.RegexValidator(message='Use a language code such as en or en-US.', regex='^[a-z]{2}(?:-[A-Z]{2})?$')])),
                ('audio_file', models.FileField(blank=True, max_length=255, upload_to=apps.listening.models.listening_audio_upload_to, validators=[django.core.validators.FileExtensionValidator(('mp3', 'wav', 'm4a', 'ogg', 'webm')), apps.listening.validators.validate_audio_file_size])),
                ('audio_stream_url', models.URLField(blank=True, max_length=2048)),
                ('source_url', models.URLField(blank=True, max_length=2048)),
                ('cover_image_url', models.URLField(blank=True, max_length=2048)),
                ('audio_attribution', models.TextField(blank=True)),
                ('duration_seconds', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1200)])),
                ('estimated_practice_minutes', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('average_words_per_minute', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('speaker_count', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('topics', models.JSONField(blank=True, default=list, validators=[apps.listening.validators.StringListValidator(max_item_length=80, max_items=20)])),
                ('vocabulary_preview', models.JSONField(blank=True, default=list, validators=[apps.listening.validators.StringListValidator(max_item_length=120, max_items=30)])),
                ('available_practice_modes', models.JSONField(default=list, validators=[apps.listening.validators.PracticeModesValidator()])),
                ('instructions', models.JSONField(blank=True, default=list, validators=[apps.listening.validators.StringListValidator(max_item_length=500, max_items=20)])),
                ('hint_words', models.JSONField(blank=True, default=list, validators=[apps.listening.validators.StringListValidator(max_item_length=120, max_items=50)])),
                ('minimum_transcript_words', models.PositiveSmallIntegerField(default=20, validators=[django.core.validators.MinValueValidator(1)])),
                ('reference_transcript', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listening_contents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'listening_contents',
                'ordering': ('-is_featured', 'cefr_level', 'title'),
                'indexes': [models.Index(fields=['is_published', 'status', 'cefr_level'], name='listen_public_level_idx'), models.Index(fields=['content_type', 'cefr_level'], name='listen_type_level_idx'), models.Index(fields=['owner', 'source_type'], name='listen_owner_source_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('duration_seconds__gt', 0), ('duration_seconds__lte', 1200)), name='listen_duration_valid'), models.CheckConstraint(condition=models.Q(('estimated_practice_minutes__gt', 0)), name='listen_practice_minutes_gt_0'), models.CheckConstraint(condition=models.Q(models.Q(('owner__isnull', True), ('source_type', 'platform')), models.Q(models.Q(('source_type', 'platform'), _negated=True), ('owner__isnull', False)), _connector='OR'), name='listen_owner_matches_source'), models.CheckConstraint(condition=models.Q(('is_published', False), ('source_type', 'platform'), _connector='OR'), name='listen_only_platform_published')],
            },
        ),
    ]
