# Generated by Django 5.2.16 on 2026-08-18 14:46

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listening', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeningAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('practice_mode', models.CharField(choices=[('listen_only', 'Listen only'), ('full_dictation', 'Full dictation'), ('guided_dictation', 'Guided dictation'), ('fill_in_the_blank', 'Fill in the blank'), ('comprehension', 'Comprehension'), ('shadowing', 'Shadowing')], max_length=24)),
                ('answer_source', models.CharField(choices=[('typed', 'Typed'), ('document', 'Document'), ('image', 'Image')], default='typed', max_length=16)),
                ('transcript', models.TextField(blank=True, max_length=20000)),
                ('current_position_seconds', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('playback_rate', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.50')), django.core.validators.MaxValueValidator(Decimal('2.00'))])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('extracting_notes', 'Extracting notes'), ('ready', 'Ready'), ('submitted', 'Submitted'), ('analyzing', 'Analyzing'), ('completed', 'Completed'), ('failed', 'Failed')], default='draft', max_length=24)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='listening.listeningcontent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'listening_attempts',
                'ordering': ('-updated_at',),
                'indexes': [models.Index(fields=['user', 'status', 'updated_at'], name='listen_attempt_user_idx'), models.Index(fields=['user', 'content', 'updated_at'], name='listen_attempt_content_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('current_position_seconds__gte', 0)), name='listen_attempt_position_gte_0'), models.CheckConstraint(condition=models.Q(('playback_rate__gte', Decimal('0.50')), ('playback_rate__lte', Decimal('2.00'))), name='listen_attempt_rate_valid'), models.UniqueConstraint(condition=models.Q(('status__in', ('draft', 'extracting_notes', 'ready'))), fields=('user', 'content', 'practice_mode'), name='listen_one_editable_attempt')],
            },
        ),
    ]
